distributable:
  url: https://github.com/phiresky/ripgrep-all/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/rga

versions:
  github: phiresky/ripgrep-all/tags

build:
  dependencies:
    rust-lang.org: '>=1.75'
    rust-lang.org/cargo: '*'
  script:
    cargo install --locked ripgrep_all
    cargo install --locked --path . --root {{prefix}}

test:
  script: |
    rga hello $FIXTURE
  fixture: |
    hello, world
